FROM ubuntu

COPY . .

RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y python3.10-venv
RUN python3 -m venv ./venv
RUN . ./venv/bin/activate
RUN pip3 install transformers
RUN pip3 install -U pip
RUN pip3 install tensorflow --no-cache-dir
RUN pip3 install rasa

CMD . ./venv/bin/activate && rasa run --model ./models/20230627-163442-maroon-bright.tar.gz --enable-api --cors "*"